<!-- promise.all -->
var accountCall = new Promise((resolve,reject) => {
    setTimeout(() => {
        console.log('account fetch successfully');
        resolve(['saving','current']);
    },1000);
});

var countryCall = new Promise((resolve,reject) => {
    setTimeout(() => {
        console.log('country list fetch successfully');
        resolve(['INDIA','AUSTRALIA']);
    },2000);
});

var currencyList = new Promise((resolve,reject) => {
    setTimeout(() => {
        console.log('currency list fetch successfully');
        resolve(['INR','USD','AUD']);
    },3000);
});

<!-- output -->
<!-- account fetch successfully -->
<!-- country list fetch successfully -->
<!-- currency list fetch successfully -->

promise.all([accountCall,countryCall,currencyList]).then(results=>{
    console.log('FORM LOADED SUCCESSFULLY',results)
})

<!-- output: FORM LOADED SUCCESSFULLY : because all the above three calls are successfully fetched-->


<!-- Now make changes to the above code -->

var accountCall = new Promise((resolve,reject) => {
    setTimeout(() => {
        console.log('account fetch successfully');
        resolve(['saving','current']);
    },1000);
});

var countryCall = new Promise((resolve,reject) => {
    setTimeout(() => {
        console.log('country list fetch successfully');
        reject('error');
    },2000);
});

var currencyList = new Promise((resolve,reject) => {
    setTimeout(() => {
        console.log('currency list fetch successfully');
        resolve(['INR','USD','AUD']);
    },3000);
});

promise.all([accountCall,countryCall,currencyList]).then(results=>{
    console.log('FORM LOADED SUCCESSFULLY',results)
}).catch(err=>{
    console.error(err)
    console.log(FORM LOADED Unsuccessfully)
})

<!-- ouptut: -->
<!-- account fetch successfully -->
<!-- country list fetch successfully -->
<!-- error -->
<!-- FORM LOADED Unsuccessfully   :one of the calls in the above scenario failed  -->
<!-- currency list fetch successfully -->
